export type CipherwordDifficulty = 1 | 2 | 3 | 4 | 5;
export type CipherwordCategory =
  | "technology"
  | "finance"
  | "science"
  | "nature"
  | "strategy"
  | "culture"
  | "language"
  | "history"
  | "design";

export const CIPHERWORD_CATEGORIES = [
  "technology",
  "finance",
  "science",
  "nature",
  "strategy",
  "culture",
  "language",
  "history",
  "design",
] as const satisfies CipherwordCategory[];

export type CipherwordPuzzle = {
  id: string;
  answer: string;
  aliases: string[];
  category: CipherwordCategory;
  difficulty: CipherwordDifficulty;
  tags: string[];
  near: string[];
  definition: string;
  learn: string;
  clueLadder?: string[];
};

const slug = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const p = (
  answer: string,
  category: CipherwordCategory,
  difficulty: CipherwordDifficulty,
  tags: string[],
  near: string[],
  definition: string,
  learn: string,
  aliases: string[] = [],
): CipherwordPuzzle => ({
  id: `cw-${slug(answer)}`,
  answer,
  aliases,
  category,
  difficulty,
  tags,
  near,
  definition,
  learn,
});

export const CIPHERWORD_SEED_PUZZLES: CipherwordPuzzle[] = [
  p(
    "cipher",
    "language",
    2,
    ["code", "secret", "letters", "pattern"],
    ["code", "secret", "decode", "encryption", "puzzle"],
    "A coded way of writing or hiding a message.",
    "Cipher names the core loop: turn noisy symbols into meaning.",
  ),
  p(
    "signal",
    "technology",
    2,
    ["information", "noise", "message", "data"],
    ["noise", "message", "alert", "indicator", "broadcast"],
    "Information that stands out from background noise.",
    "Signal is useful because it separates meaning from clutter.",
  ),
  p(
    "orbit",
    "science",
    2,
    ["space", "path", "gravity", "motion"],
    ["planet", "space", "cycle", "rotation", "satellite"],
    "A curved path around a body in space.",
    "An orbit is a path, not the object moving through it.",
  ),
  p(
    "catalyst",
    "science",
    3,
    ["reaction", "change", "chemistry", "accelerator"],
    ["spark", "enzyme", "trigger", "accelerant", "reaction"],
    "Something that speeds up change without being consumed.",
    "Catalyst moved from chemistry into business and culture as a word for a change trigger.",
  ),
  p(
    "latency",
    "technology",
    3,
    ["delay", "network", "speed", "response"],
    ["lag", "delay", "ping", "network", "slow"],
    "The delay before a transfer or response begins.",
    "Low latency makes interfaces feel instant even when bandwidth is unchanged.",
  ),
  p(
    "proxy",
    "technology",
    2,
    ["representative", "network", "substitute", "access"],
    ["agent", "stand-in", "server", "vpn", "delegate"],
    "A substitute that acts on behalf of something else.",
    "Proxy works in both networking and decision-making because both involve indirect action.",
  ),
  p(
    "fulcrum",
    "science",
    4,
    ["pivot", "lever", "balance", "force"],
    ["pivot", "lever", "hinge", "balance", "axis"],
    "The support point on which a lever turns.",
    "The fulcrum is small but decides how force gets amplified.",
  ),
  p(
    "entropy",
    "science",
    4,
    ["disorder", "physics", "energy", "uncertainty"],
    ["chaos", "disorder", "decay", "thermodynamics", "randomness"],
    "A measure associated with disorder, uncertainty, or unavailable energy.",
    "Entropy became a metaphor for systems becoming harder to organize over time.",
  ),
  p(
    "leverage",
    "finance",
    3,
    ["debt", "force", "amplify", "finance"],
    ["debt", "borrow", "amplify", "margin", "power"],
    "Using a tool, position, or borrowed money to amplify an outcome.",
    "Leverage can magnify gains and losses, which is why it feels powerful and dangerous.",
  ),
  p(
    "runway",
    "finance",
    2,
    ["startup", "cash", "time", "survival"],
    ["cash", "burn", "months", "startup", "lifeline"],
    "The amount of time a project can continue before resources run out.",
    "Startup runway turns a cash balance into a time limit.",
  ),
  p(
    "margin",
    "finance",
    2,
    ["profit", "space", "buffer", "finance"],
    ["profit", "spread", "buffer", "edge", "markup"],
    "The space between cost and result, price and expense, or safety and failure.",
    "Margin is useful because it describes both money and room for error.",
  ),
  p(
    "anomaly",
    "science",
    3,
    ["outlier", "pattern", "unexpected", "data"],
    ["outlier", "glitch", "exception", "irregularity", "oddity"],
    "Something that does not fit the expected pattern.",
    "An anomaly is often the first clue that a model is incomplete.",
  ),
  p(
    "vector",
    "science",
    3,
    ["direction", "magnitude", "math", "movement"],
    ["arrow", "direction", "force", "coordinate", "embedding"],
    "A quantity with both magnitude and direction.",
    "Vector now bridges math, physics, graphics, and machine learning.",
  ),
  p(
    "mosaic",
    "design",
    2,
    ["pattern", "tiles", "image", "composition"],
    ["tiles", "collage", "pattern", "fragments", "picture"],
    "A larger image built from many small pieces.",
    "Mosaic is a clean metaphor for many fragments forming one whole.",
  ),
  p(
    "prism",
    "science",
    2,
    ["light", "color", "refraction", "glass"],
    ["rainbow", "light", "lens", "spectrum", "glass"],
    "A transparent object that bends and separates light.",
    "A prism turns hidden parts of light into something visible.",
  ),
  p(
    "anchor",
    "strategy",
    2,
    ["stability", "bias", "reference", "hold"],
    ["hold", "bias", "reference", "mooring", "baseline"],
    "A point that holds something in place or frames later judgment.",
    "Anchoring matters because first numbers or ideas can pull later decisions toward them.",
  ),
  p(
    "cadence",
    "design",
    3,
    ["rhythm", "pace", "sequence", "repeat"],
    ["rhythm", "tempo", "pace", "cycle", "beat"],
    "A rhythm or repeated pattern of movement, sound, or work.",
    "Good cadence makes complex work feel predictable.",
  ),
  p(
    "pulse",
    "science",
    1,
    ["rhythm", "beat", "signal", "life"],
    ["beat", "heartbeat", "wave", "rhythm", "signal"],
    "A short beat, wave, or repeated signal.",
    "Pulse is simple, physical, and easy to extend into product or systems language.",
  ),
  p(
    "threshold",
    "science",
    3,
    ["limit", "boundary", "trigger", "change"],
    ["limit", "edge", "trigger", "boundary", "minimum"],
    "The point at which a change begins or a condition is met.",
    "Thresholds create sudden shifts from gradual pressure.",
  ),
  p(
    "nexus",
    "strategy",
    4,
    ["connection", "center", "network", "link"],
    ["hub", "link", "center", "junction", "network"],
    "A central connection point between things.",
    "Nexus sounds abstract, but it simply means the place where important links meet.",
  ),
  p(
    "drift",
    "science",
    2,
    ["movement", "slow", "change", "direction"],
    ["slide", "shift", "current", "wander", "float"],
    "A slow movement away from an original position or course.",
    "Drift can be physical, strategic, or cultural.",
  ),
  p(
    "vertex",
    "science",
    4,
    ["point", "geometry", "corner", "graph"],
    ["corner", "node", "point", "angle", "graph"],
    "A point where edges meet in a shape or graph.",
    "Vertex is useful in geometry, networks, and computer graphics.",
  ),
  p(
    "horizon",
    "nature",
    2,
    ["distance", "view", "limit", "future"],
    ["skyline", "distance", "future", "edge", "view"],
    "The line where earth and sky appear to meet.",
    "Horizon is both a visual boundary and a metaphor for what is coming.",
  ),
  p(
    "scaffold",
    "design",
    3,
    ["structure", "support", "temporary", "building"],
    ["framework", "support", "structure", "skeleton", "platform"],
    "A temporary support structure used while something is being built.",
    "Scaffolds disappear after they help stronger structures stand.",
  ),
  p(
    "blueprint",
    "design",
    2,
    ["plan", "design", "architecture", "map"],
    ["plan", "map", "schematic", "design", "draft"],
    "A detailed plan for building something.",
    "Blueprint survives as a metaphor even though literal blueprints are less common now.",
  ),
  p(
    "aperture",
    "design",
    4,
    ["opening", "camera", "light", "lens"],
    ["lens", "opening", "camera", "light", "shutter"],
    "An opening that controls how much light passes through.",
    "Aperture changes exposure and depth of field, making it a technical and creative control.",
  ),
  p(
    "velocity",
    "science",
    3,
    ["speed", "direction", "motion", "rate"],
    ["speed", "pace", "motion", "momentum", "rate"],
    "Speed in a particular direction.",
    "Velocity is not just speed; direction is part of the idea.",
  ),
  p(
    "resonance",
    "science",
    4,
    ["vibration", "frequency", "response", "meaning"],
    ["echo", "frequency", "vibration", "harmony", "reverberation"],
    "A strong response when frequencies or meanings align.",
    "Resonance explains physical vibration and why some ideas feel emotionally right.",
  ),
  p(
    "friction",
    "strategy",
    2,
    ["resistance", "drag", "difficulty", "motion"],
    ["resistance", "drag", "roughness", "obstacle", "slowdown"],
    "Resistance that slows motion, action, or adoption.",
    "Removing friction is one of the simplest ways to improve a product.",
  ),
  p(
    "shadow",
    "culture",
    2,
    ["dark", "trace", "hidden", "shape"],
    ["shade", "darkness", "trace", "silhouette", "hidden"],
    "A dark shape made when light is blocked.",
    "Shadow works as a physical image and a metaphor for what follows or hides.",
  ),
  p(
    "keystone",
    "design",
    4,
    ["arch", "support", "central", "structure"],
    ["arch", "support", "centerpiece", "cornerstone", "stone"],
    "The central stone that locks an arch in place.",
    "Keystone became a metaphor for the part that keeps the whole system together.",
  ),
  p(
    "compass",
    "strategy",
    2,
    ["direction", "navigation", "north", "guide"],
    ["map", "north", "guide", "navigation", "direction"],
    "A tool or principle that helps determine direction.",
    "A compass gives orientation, not the full route.",
  ),
  p(
    "paradox",
    "language",
    4,
    ["contradiction", "logic", "surprise", "truth"],
    ["contradiction", "puzzle", "irony", "dilemma", "logic"],
    "A statement or situation that seems contradictory but may reveal truth.",
    "Paradoxes are sticky because they make logic feel unstable.",
  ),
  p(
    "sentinel",
    "technology",
    4,
    ["watcher", "guard", "alert", "security"],
    ["guard", "watcher", "monitor", "lookout", "protector"],
    "A guard or watcher placed to detect danger.",
    "Sentinel has moved from watchtowers into cybersecurity and monitoring tools.",
  ),
  p(
    "gradient",
    "design",
    3,
    ["change", "slope", "color", "math"],
    ["slope", "fade", "color", "transition", "rate"],
    "A gradual change across distance, value, or color.",
    "Gradient connects calculus, maps, and modern interface design.",
  ),
  p(
    "circuit",
    "technology",
    2,
    ["electric", "loop", "path", "system"],
    ["loop", "wire", "electric", "board", "path"],
    "A closed path through which electricity or signals can flow.",
    "Circuits are useful because they turn paths into behavior.",
  ),
  p(
    "isotope",
    "science",
    4,
    ["atom", "neutron", "element", "variant"],
    ["atom", "element", "nucleus", "variant", "carbon"],
    "A variant of an element with a different number of neutrons.",
    "Isotopes show that the same element can have different nuclear identities.",
  ),
  p(
    "membrane",
    "science",
    3,
    ["barrier", "cell", "filter", "surface"],
    ["cell", "barrier", "skin", "filter", "layer"],
    "A thin layer that separates or filters spaces.",
    "Membranes matter because they control what crosses a boundary.",
  ),
  p(
    "spectrum",
    "science",
    3,
    ["range", "light", "color", "continuum"],
    ["range", "rainbow", "continuum", "light", "scale"],
    "A continuous range of values, colors, or possibilities.",
    "Spectrum makes categories feel less binary.",
  ),
  p(
    "gravity",
    "science",
    2,
    ["force", "mass", "pull", "space"],
    ["pull", "force", "mass", "orbit", "weight"],
    "The attractive force between masses.",
    "Gravity is invisible, but its effects define motion at every scale.",
  ),
  p(
    "eclipse",
    "science",
    2,
    ["shadow", "moon", "sun", "alignment"],
    ["moon", "sun", "shadow", "alignment", "darkening"],
    "When one celestial body blocks light from another.",
    "An eclipse is dramatic because alignment briefly changes what can be seen.",
  ),
  p(
    "tundra",
    "nature",
    3,
    ["cold", "plain", "arctic", "biome"],
    ["arctic", "cold", "permafrost", "plain", "biome"],
    "A cold treeless biome with low vegetation.",
    "Tundra looks empty but holds specialized life.",
  ),
  p(
    "monsoon",
    "nature",
    3,
    ["rain", "season", "wind", "climate"],
    ["rain", "season", "storm", "wind", "downpour"],
    "A seasonal wind pattern often bringing heavy rain.",
    "Monsoon is not just rain; it is a seasonal atmospheric system.",
  ),
  p(
    "delta",
    "nature",
    2,
    ["river", "change", "mouth", "triangle"],
    ["river", "change", "triangle", "mouth", "sediment"],
    "Landform at a river mouth, or a symbol for change.",
    "Delta works in geography, math, finance, and shorthand for difference.",
  ),
  p(
    "cavern",
    "nature",
    2,
    ["cave", "underground", "stone", "dark"],
    ["cave", "underground", "chamber", "stone", "hollow"],
    "A large cave or underground chamber.",
    "Caverns feel mysterious because they are rooms carved by deep time.",
  ),
  p(
    "canopy",
    "nature",
    2,
    ["forest", "cover", "trees", "roof"],
    ["forest", "trees", "cover", "roof", "shade"],
    "The upper covering formed by tree crowns or overhead fabric.",
    "A canopy controls light, shade, and life beneath it.",
  ),
  p(
    "glacier",
    "nature",
    3,
    ["ice", "slow", "mass", "mountain"],
    ["ice", "snow", "mountain", "flow", "frozen"],
    "A huge slow-moving mass of ice.",
    "Glaciers are moving systems even when they look still.",
  ),
  p(
    "ember",
    "nature",
    2,
    ["fire", "glow", "heat", "remnant"],
    ["spark", "coal", "glow", "fire", "ash"],
    "A small glowing piece left from a fire.",
    "Embers suggest both ending and possible renewal.",
  ),
  p(
    "kelp",
    "nature",
    2,
    ["ocean", "seaweed", "forest", "marine"],
    ["seaweed", "ocean", "algae", "marine", "forest"],
    "Large brown seaweed that can form underwater forests.",
    "Kelp forests are marine habitats, not just sea plants.",
  ),
  p(
    "quartz",
    "nature",
    3,
    ["mineral", "crystal", "stone", "silica"],
    ["crystal", "stone", "mineral", "silica", "gem"],
    "A common hard mineral made of silicon dioxide.",
    "Quartz is common but visually iconic because it forms clear crystals.",
  ),
  p(
    "pollen",
    "nature",
    2,
    ["plant", "dust", "flower", "reproduction"],
    ["flower", "dust", "allergy", "plant", "bee"],
    "Fine powder from seed plants used in reproduction.",
    "Pollen is tiny but drives huge seasonal and ecological cycles.",
  ),
  p(
    "meadow",
    "nature",
    2,
    ["field", "grass", "flowers", "open"],
    ["field", "grass", "flowers", "pasture", "open"],
    "An open grassy area, often with wildflowers.",
    "Meadow is a quiet word with strong visual pull.",
  ),
  p(
    "citadel",
    "history",
    4,
    ["fortress", "city", "defense", "stronghold"],
    ["fortress", "castle", "stronghold", "wall", "bastion"],
    "A fortress protecting or dominating a city.",
    "Citadels show how architecture and power overlap.",
  ),
  p(
    "archive",
    "history",
    2,
    ["records", "memory", "storage", "past"],
    ["records", "library", "storage", "history", "memory"],
    "A collection of records preserved for reference.",
    "Archives decide what survives as memory.",
  ),
  p(
    "oracle",
    "history",
    3,
    ["prophecy", "wisdom", "answer", "ancient"],
    ["prophet", "seer", "prediction", "answer", "delphi"],
    "A source of prophecy, wisdom, or authoritative answers.",
    "Oracle moved from ancient religion into databases, fiction, and tech metaphors.",
  ),
  p(
    "empire",
    "history",
    2,
    ["power", "territory", "rule", "state"],
    ["kingdom", "power", "territory", "rule", "dynasty"],
    "A large political unit ruled by central authority.",
    "Empire is a historical structure and a modern metaphor for dominance.",
  ),
  p(
    "treaty",
    "history",
    2,
    ["agreement", "states", "peace", "diplomacy"],
    ["agreement", "pact", "peace", "deal", "accord"],
    "A formal agreement between states or groups.",
    "Treaties turn conflict or negotiation into written obligations.",
  ),
  p(
    "senate",
    "history",
    2,
    ["government", "council", "rome", "law"],
    ["council", "government", "rome", "lawmakers", "chamber"],
    "A deliberative governing council or legislative chamber.",
    "Senate comes from ancient political forms that still shape modern institutions.",
  ),
  p(
    "caravan",
    "history",
    3,
    ["travel", "trade", "desert", "group"],
    ["trade", "desert", "wagons", "journey", "convoy"],
    "A group traveling together, often for trade or safety.",
    "Caravans made long-distance exchange possible before modern transport.",
  ),
  p(
    "alpha",
    "finance",
    3,
    ["performance", "edge", "market", "return"],
    ["edge", "outperformance", "return", "fund", "market"],
    "Return above a benchmark or a sign of edge.",
    "Alpha is compelling because it names skill after removing the market baseline.",
  ),
  p(
    "beta",
    "finance",
    2,
    ["market", "risk", "volatility", "exposure"],
    ["risk", "volatility", "market", "exposure", "index"],
    "A measure of sensitivity to market movement.",
    "Beta is about exposure to the broader market, not individual skill.",
  ),
  p(
    "hedge",
    "finance",
    2,
    ["risk", "protection", "offset", "trade"],
    ["protection", "insurance", "offset", "risk", "short"],
    "A position or action used to reduce risk.",
    "A hedge limits downside, often by giving up some upside.",
  ),
  p(
    "arbitrage",
    "finance",
    4,
    ["price", "spread", "market", "inefficiency"],
    ["spread", "mispricing", "trade", "market", "profit"],
    "Profiting from price differences across markets.",
    "Arbitrage pressures prices toward consistency.",
  ),
  p(
    "liquidity",
    "finance",
    3,
    ["cash", "market", "ease", "selling"],
    ["cash", "volume", "market", "sell", "depth"],
    "How easily an asset can be converted to cash without moving price.",
    "Liquidity is invisible until you need to exit.",
  ),
  p(
    "dividend",
    "finance",
    2,
    ["income", "shareholder", "stock", "cash"],
    ["payout", "income", "stock", "shareholder", "yield"],
    "A payment from a company to its shareholders.",
    "Dividends turn ownership into direct cash return.",
  ),
  p(
    "equity",
    "finance",
    2,
    ["ownership", "stock", "value", "stake"],
    ["ownership", "stake", "shares", "stock", "capital"],
    "Ownership value in an asset or company.",
    "Equity means owning the residual claim after debts.",
  ),
  p(
    "option",
    "finance",
    3,
    ["right", "contract", "strike", "choice"],
    ["contract", "strike", "call", "put", "choice"],
    "A contract giving the right, not obligation, to buy or sell.",
    "Options are valuable because choice under uncertainty has a price.",
  ),
  p(
    "moat",
    "finance",
    3,
    ["advantage", "defense", "business", "durability"],
    ["advantage", "barrier", "defense", "castle", "competition"],
    "A durable advantage that protects a business from competition.",
    "Moat turns a medieval defense image into business strategy.",
  ),
  p(
    "tailwind",
    "finance",
    3,
    ["support", "trend", "growth", "momentum"],
    ["boost", "trend", "support", "momentum", "wind"],
    "A condition that helps progress or growth.",
    "Tailwinds make forward motion easier without changing the engine.",
  ),
  p(
    "collateral",
    "finance",
    3,
    ["loan", "security", "asset", "pledge"],
    ["asset", "loan", "pledge", "security", "guarantee"],
    "An asset pledged to secure a loan.",
    "Collateral changes lending because it gives the lender a fallback claim.",
  ),
  p(
    "premium",
    "finance",
    2,
    ["price", "insurance", "extra", "option"],
    ["extra", "price", "insurance", "option", "cost"],
    "An extra price paid above a base amount, or an insurance/option cost.",
    "Premium always implies paying more for a specific advantage or protection.",
  ),
  p(
    "yield",
    "finance",
    2,
    ["income", "return", "bond", "rate"],
    ["return", "income", "rate", "bond", "interest"],
    "Income return on an investment, usually shown as a rate.",
    "Yield focuses on cash generated, not just price change.",
  ),
  p(
    "coupon",
    "finance",
    3,
    ["bond", "interest", "payment", "rate"],
    ["bond", "interest", "payment", "yield", "note"],
    "The regular interest payment on a bond.",
    "Coupon survives from paper bonds that had detachable payment coupons.",
  ),
  p(
    "spread",
    "finance",
    3,
    ["difference", "price", "rate", "gap"],
    ["gap", "difference", "bid", "ask", "margin"],
    "The gap between two prices, rates, or values.",
    "Spreads reveal cost, risk, and disagreement.",
  ),
  p(
    "drawdown",
    "finance",
    4,
    ["loss", "decline", "portfolio", "risk"],
    ["loss", "decline", "drop", "portfolio", "peak"],
    "The decline from a peak to a lower value.",
    "Drawdown measures pain better than volatility alone.",
  ),
  p(
    "valuation",
    "finance",
    3,
    ["worth", "price", "company", "estimate"],
    ["worth", "price", "estimate", "multiple", "appraisal"],
    "An estimate of what an asset or company is worth.",
    "Valuation is where narrative and numbers collide.",
  ),
  p(
    "multiple",
    "finance",
    4,
    ["ratio", "valuation", "earnings", "price"],
    ["ratio", "valuation", "pe", "earnings", "compare"],
    "A valuation ratio comparing price to a business metric.",
    "Multiples compress a business story into a comparable number.",
  ),
  p(
    "covenant",
    "finance",
    4,
    ["agreement", "loan", "restriction", "promise"],
    ["promise", "loan", "agreement", "restriction", "term"],
    "A binding promise or restriction in an agreement.",
    "Loan covenants are early-warning systems for lenders.",
  ),
  p(
    "metaphor",
    "language",
    2,
    ["comparison", "meaning", "image", "language"],
    ["comparison", "symbol", "image", "figure", "analogy"],
    "A figure of speech that describes one thing as another.",
    "Metaphor lets language transfer understanding from one domain to another.",
  ),
  p(
    "irony",
    "language",
    2,
    ["contrast", "meaning", "unexpected", "speech"],
    ["sarcasm", "contrast", "twist", "unexpected", "opposite"],
    "A contrast between expectation and reality or literal and intended meaning.",
    "Irony works because the surface meaning is not the whole meaning.",
  ),
  p(
    "idiom",
    "language",
    2,
    ["phrase", "meaning", "expression", "culture"],
    ["phrase", "expression", "saying", "slang", "meaning"],
    "An expression whose meaning is not obvious from its individual words.",
    "Idioms make language feel local and lived-in.",
  ),
  p(
    "nuance",
    "language",
    3,
    ["subtle", "difference", "meaning", "shade"],
    ["subtlety", "shade", "detail", "difference", "precision"],
    "A subtle difference in meaning, feeling, or tone.",
    "Nuance is what keeps good judgment from becoming blunt.",
  ),
  p(
    "motif",
    "culture",
    3,
    ["theme", "pattern", "recurring", "art"],
    ["theme", "pattern", "symbol", "recurring", "design"],
    "A recurring element, image, or theme in art or design.",
    "Motifs make repetition feel intentional.",
  ),
  p(
    "allegory",
    "culture",
    4,
    ["symbol", "story", "meaning", "lesson"],
    ["symbol", "fable", "metaphor", "parable", "story"],
    "A story or image with a second symbolic meaning.",
    "Allegory hides an argument inside a narrative.",
  ),
  p(
    "canon",
    "culture",
    3,
    ["official", "works", "story", "accepted"],
    ["official", "lore", "works", "standard", "accepted"],
    "The accepted body of works, rules, or story material.",
    "Canon decides what counts as official inside a tradition or fandom.",
  ),
  p(
    "folklore",
    "culture",
    3,
    ["tradition", "stories", "people", "myth"],
    ["myth", "legend", "tradition", "story", "custom"],
    "Traditional stories, beliefs, and customs passed through a culture.",
    "Folklore preserves what communities repeat before they write it down.",
  ),
  p(
    "sonnet",
    "language",
    3,
    ["poem", "fourteen", "rhyme", "literature"],
    ["poem", "rhyme", "verse", "shakespeare", "fourteen"],
    "A structured fourteen-line poem.",
    "The sonnet survives because strict limits can sharpen emotion.",
  ),
  p(
    "syntax",
    "language",
    3,
    ["grammar", "order", "sentence", "code"],
    ["grammar", "order", "sentence", "structure", "code"],
    "The arrangement of words, symbols, or code into valid structure.",
    "Syntax matters in both language and programming because order creates meaning.",
  ),
  p(
    "dialect",
    "language",
    3,
    ["speech", "region", "variation", "language"],
    ["accent", "speech", "region", "variation", "language"],
    "A regional or social variety of a language.",
    "Dialects show that language changes with people and place.",
  ),
  p(
    "subtext",
    "language",
    4,
    ["hidden", "meaning", "dialogue", "implication"],
    ["hidden", "implication", "undertone", "meaning", "between lines"],
    "Meaning implied beneath what is directly said.",
    "Subtext is why a simple line can carry tension.",
  ),
  p(
    "rhetoric",
    "language",
    4,
    ["persuasion", "speech", "argument", "style"],
    ["persuasion", "speech", "argument", "style", "oratory"],
    "The art or technique of persuasive language.",
    "Rhetoric studies how language moves people, not just what it states.",
  ),
  p(
    "cache",
    "technology",
    2,
    ["storage", "speed", "memory", "reuse"],
    ["memory", "storage", "buffer", "browser", "fast"],
    "A temporary storage layer used to retrieve data faster.",
    "Caching trades freshness complexity for speed.",
  ),
  p(
    "token",
    "technology",
    2,
    ["access", "unit", "security", "text"],
    ["key", "access", "unit", "auth", "coin"],
    "A small unit representing access, value, identity, or text.",
    "Token means different things in security, crypto, and language models, but always represents something compact.",
  ),
  p(
    "kernel",
    "technology",
    4,
    ["core", "operating", "system", "control"],
    ["core", "os", "system", "linux", "control"],
    "The core part of an operating system.",
    "The kernel sits between hardware and software, quietly controlling the system.",
  ),
  p(
    "protocol",
    "technology",
    3,
    ["rules", "network", "communication", "standard"],
    ["rules", "standard", "network", "handshake", "communication"],
    "A set of rules for communication or procedure.",
    "Protocols let different systems cooperate without improvising every interaction.",
  ),
  p(
    "sandbox",
    "technology",
    3,
    ["isolation", "security", "test", "environment"],
    ["isolation", "test", "security", "container", "safe"],
    "An isolated environment for testing or restricting behavior.",
    "A sandbox lets risky actions happen without damaging the main system.",
  ),
  p(
    "packet",
    "technology",
    3,
    ["network", "data", "unit", "transfer"],
    ["data", "network", "message", "unit", "router"],
    "A small unit of data sent across a network.",
    "The internet moves by breaking communication into packets.",
  ),
  p(
    "stack",
    "technology",
    2,
    ["layers", "software", "collection", "structure"],
    ["layers", "tools", "software", "pile", "framework"],
    "A layered set of technologies or an ordered data structure.",
    "Stack is useful because modern software is built in layers.",
  ),
  p(
    "commit",
    "technology",
    2,
    ["git", "change", "record", "code"],
    ["git", "change", "save", "version", "code"],
    "A recorded change in version control.",
    "A commit is a snapshot of intent, not just a save button.",
  ),
  p(
    "compile",
    "technology",
    3,
    ["code", "build", "translate", "program"],
    ["build", "code", "translate", "program", "compiler"],
    "To translate code into a form a machine or runtime can use.",
    "Compile errors feel annoying because they stop intent before execution.",
  ),
  p(
    "runtime",
    "technology",
    3,
    ["execution", "program", "environment", "code"],
    ["execution", "environment", "program", "node", "process"],
    "The environment or period in which code executes.",
    "Runtime is where code stops being static and starts behaving.",
  ),
  p(
    "cursor",
    "technology",
    2,
    ["pointer", "position", "interface", "text"],
    ["pointer", "caret", "mouse", "position", "selection"],
    "A marker showing position in an interface, text field, or data set.",
    "Cursor is a tiny interface object that controls attention.",
  ),
  p(
    "branch",
    "technology",
    2,
    ["git", "path", "version", "split"],
    ["git", "version", "split", "path", "tree"],
    "A separate line of development or a split path.",
    "Branches let teams explore without immediately changing the main line.",
  ),
  p(
    "render",
    "technology",
    2,
    ["display", "draw", "ui", "output"],
    ["draw", "display", "paint", "screen", "ui"],
    "To generate visible output from data or instructions.",
    "Rendering turns state into what the user can actually see.",
  ),
  p(
    "gambit",
    "strategy",
    4,
    ["sacrifice", "opening", "chess", "advantage"],
    ["sacrifice", "chess", "opening", "move", "trade"],
    "A risky opening move that sacrifices something for advantage.",
    "Gambit is attractive because it makes risk look intentional.",
  ),
  p(
    "decoy",
    "strategy",
    2,
    ["misdirection", "target", "bait", "strategy"],
    ["bait", "fake", "trap", "misdirection", "lure"],
    "Something used to distract attention from the real target.",
    "Decoys exploit attention as much as information.",
  ),
  p(
    "flank",
    "strategy",
    3,
    ["side", "attack", "military", "angle"],
    ["side", "angle", "attack", "maneuver", "wing"],
    "The side of a formation or position.",
    "Flanking works because defenders usually face the obvious direction.",
  ),
  p(
    "bottleneck",
    "strategy",
    3,
    ["constraint", "slow", "capacity", "process"],
    ["constraint", "choke", "capacity", "slowdown", "queue"],
    "The narrowest constraint limiting throughput.",
    "Improving non-bottlenecks often changes nothing.",
  ),
  p(
    "triage",
    "strategy",
    3,
    ["priority", "urgent", "decision", "limited"],
    ["priority", "sort", "urgent", "hospital", "ranking"],
    "Sorting problems by urgency when resources are limited.",
    "Triage is a decision system for pressure.",
  ),
  p(
    "pivot",
    "strategy",
    2,
    ["change", "turn", "strategy", "startup"],
    ["turn", "change", "shift", "startup", "axis"],
    "A strategic change in direction while keeping some base intact.",
    "A pivot is not random change; it rotates around something retained.",
  ),
  p(
    "blitz",
    "strategy",
    2,
    ["fast", "attack", "speed", "burst"],
    ["rush", "attack", "fast", "burst", "sprint"],
    "A sudden intense effort or attack.",
    "Blitz makes speed the strategy.",
  ),
  p(
    "stalemate",
    "strategy",
    3,
    ["deadlock", "chess", "no move", "draw"],
    ["deadlock", "draw", "chess", "gridlock", "impasse"],
    "A deadlock where no side can make a winning move.",
    "Stalemate is not victory; it is motion trapped by rules.",
  ),
  p(
    "checkpoint",
    "strategy",
    2,
    ["progress", "save", "review", "marker"],
    ["marker", "save", "progress", "gate", "review"],
    "A point used to mark, verify, or resume progress.",
    "Checkpoints turn long work into recoverable segments.",
  ),
  p(
    "black swan",
    "finance",
    4,
    ["rare", "event", "risk", "surprise"],
    ["crash", "surprise", "rare", "risk", "shock"],
    "A rare, high-impact event that seems obvious only after it happens.",
    "The phrase became a major risk metaphor because it attacks false certainty.",
    ["blackswan"],
  ),
  p(
    "red herring",
    "language",
    3,
    ["misdirection", "clue", "false", "mystery"],
    ["decoy", "false clue", "misdirection", "bait", "distraction"],
    "A misleading clue that pulls attention away from the truth.",
    "Red herring is one of the cleanest names for deliberate distraction.",
    ["redherring"],
  ),
  p(
    "glass ceiling",
    "culture",
    3,
    ["barrier", "career", "invisible", "limit"],
    ["barrier", "limit", "career", "promotion", "invisible"],
    "An invisible barrier that limits advancement.",
    "The phrase works because the barrier can be unseen but still solid.",
    ["glassceiling"],
  ),
  p(
    "network effect",
    "technology",
    4,
    ["users", "value", "platform", "growth"],
    ["platform", "users", "scale", "moat", "viral"],
    "When a product becomes more valuable as more people use it.",
    "Network effects create compounding advantage when participation increases utility.",
    ["networkeffect"],
  ),
  p(
    "zero sum",
    "strategy",
    3,
    ["competition", "tradeoff", "winner", "loser"],
    ["winner", "loser", "tradeoff", "competition", "fixed pie"],
    "A situation where one side's gain equals another side's loss.",
    "Zero-sum framing can clarify conflict or wrongly hide opportunities for expansion.",
    ["zerosum"],
  ),
  p(
    "flywheel",
    "strategy",
    3,
    ["momentum", "loop", "growth", "system"],
    ["momentum", "loop", "engine", "cycle", "growth"],
    "A system that builds momentum as each turn reinforces the next.",
    "Flywheels are powerful because the hard early pushes can later compound.",
  ),
  p(
    "tipping point",
    "science",
    4,
    ["threshold", "change", "cascade", "moment"],
    ["threshold", "cascade", "breakpoint", "shift", "moment"],
    "The critical moment when small changes trigger a larger shift.",
    "A tipping point is where gradual pressure becomes visible change.",
    ["tippingpoint"],
  ),
  p(
    "velvet rope",
    "culture",
    3,
    ["exclusive", "access", "status", "club"],
    ["exclusive", "access", "club", "status", "gate"],
    "A symbol of selective access or exclusivity.",
    "The velvet rope turns physical entry control into social status language.",
    ["velvetrope"],
  ),
  p(
    "rabbit hole",
    "culture",
    3,
    ["deep", "search", "obsession", "discovery"],
    ["deep dive", "obsession", "search", "maze", "internet"],
    "A path that leads deeper into complexity or obsession.",
    "Rabbit hole became internet-native shorthand for curiosity that keeps unfolding.",
    ["rabbithole"],
  ),
  p(
    "moonshot",
    "technology",
    3,
    ["ambition", "risk", "innovation", "space"],
    ["ambition", "bold", "risk", "space", "innovation"],
    "An ambitious, difficult project with outsized potential.",
    "Moonshot inherits its force from the Apollo program and applies it to bold bets.",
  ),
  p(
    "north star",
    "strategy",
    3,
    ["guide", "direction", "metric", "goal"],
    ["guide", "goal", "direction", "metric", "compass"],
    "A guiding goal, principle, or metric.",
    "North Star works because it gives direction even when the path changes.",
    ["northstar"],
  ),
];

export const CIPHERWORD_VERSION = "2026-06-01-seed-124";
